version: "3.0"

services:
  web:
    container_name: "aarvitrage-web"
    build:
      context: ./lib/web

  api:
    container_name: "aarvitrage-api"
    networks:
      - proxy
    build:
      context: ./lib/api
