version: "3.0"

services:
  web:
    container_name: aarvitrage-web
    ports:
      - 3000:3000
    build:
      context: ./lib/web
    volumes:
      - ./lib/web:/app

  api:
    container_name: aarvitrage-api
    ports:
      - 4000:4000
    build:
      context: ./lib/api
    volumes:
      - ./lib/api:/app

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aarvitrage
      POSTGRES_PASSWORD: aarvitrage
      POSTGRES_DB: aarvitrage
